// Hotel Information
export const HOTEL_INFO = {
  name: 'Lab e Joo',
  fullName: 'Lab E Jou Resorts',
  tagline: 'Where Mountains Meet Hospitality',
  founder: 'Khan Family',
  description: 'A hidden gem in Jabbori, Pakistan. Authentic Pashtun hospitality in the Hindu Kush mountains.',
  founded: 1972,
  
  // Contact
  phone: '+92 313 5802587',
  whatsapp: '+92 313 5802587',
  email: 'qasimshabbier@gmail.com',
  
  // Location
  location: {
    town: 'Jabbori',
    region: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.6051,
    longitude: 73.2584,
    mapPlusCode: 'J734+VPP',
    elevation: '7,200 ft (2,195 m)',
    distanceFromIslamabad: '75.9 miles (3 hours drive)',
    nearestCity: 'Peshawar (90 km)',
  },
  
  // Rooms (16 total)
  rooms: [
    {
      id: 1,
      name: "The Raven's Rest",
      description: 'Named after a local legend',
      quote: '"Great view and great newly constructed rooms, staff was very professional."',
      author: 'Verified Traveler',
    },
    {
      id: 2,
      name: "Shepherd's Refuge",
      description: 'Overlooks grazing lands',
      quote: '"Not only is it just a three-hour drive from Islamabad, but it also boasts a more remarkable and pristine environment."',
      author: 'Verified Traveler',
    },
    {
      id: 3,
      name: 'Woodsmoke & Quiet',
      description: 'Minimalist, fireplace-focused',
      quote: '"Clean environment, attractive views."',
      author: 'Verified Traveler',
    },
    {
      id: 4,
      name: 'The Starwell',
      description: 'Rooftop suite, minimal light pollution',
      quote: '"The stars here are unreal. Worth every minute of the drive."',
      author: 'Verified Traveler',
    },
    {
      id: 5,
      name: 'Summit View',
      description: 'Panoramic mountain vistas',
      quote: '"Waking up to these mountains is a spiritual experience."',
      author: 'Verified Traveler',
    },
    {
      id: 6,
      name: 'Golden Dawn',
      description: 'East-facing sunrise suite',
      quote: '"Each sunrise was better than the last."',
      author: 'Verified Traveler',
    },
    {
      id: 7,
      name: 'Mountain Whisper',
      description: 'Intimate, valley-view room',
      quote: '"I felt the world slow down here."',
      author: 'Verified Traveler',
    },
    {
      id: 8,
      name: 'Harmony Haven',
      description: 'Peaceful retreat with garden access',
      quote: '"The hospitality was beyond expectations."',
      author: 'Verified Traveler',
    },
    {
      id: 9,
      name: 'Stone Path Lodge',
      description: 'Traditional architecture with modern comfort',
      quote: '"Authentic and welcoming beyond measure."',
      author: 'Verified Traveler',
    },
    {
      id: 10,
      name: 'Eagle\'s Nest',
      description: 'High altitude retreat with panoramic views',
      quote: '"Feeling closer to the sky than ever before."',
      author: 'Verified Traveler',
    },
    {
      id: 11,
      name: 'Valley Whispers',
      description: 'Nestled in the heart of the mountains',
      quote: '"Nature embracing you from every angle."',
      author: 'Verified Traveler',
    },
    {
      id: 12,
      name: 'Pine Haven',
      description: 'Surrounded by ancient pine forests',
      quote: '"The scent of the mountains, the silence of peace."',
      author: 'Verified Traveler',
    },
    {
      id: 13,
      name: 'Star Chamber',
      description: 'Perfect for stargazing and meditation',
      quote: '"Reconnecting with the universe felt natural here."',
      author: 'Verified Traveler',
    },
    {
      id: 14,
      name: 'Horizon House',
      description: 'Endless mountain views in every direction',
      quote: '"Where earth meets sky, the soul finds peace."',
      author: 'Verified Traveler',
    },
    {
      id: 15,
      name: 'Serenity Suite',
      description: 'Designed for ultimate relaxation',
      quote: '"Every moment here feels like meditation."',
      author: 'Verified Traveler',
    },
    {
      id: 16,
      name: 'Heritage House',
      description: 'Celebrates Pashtun cultural traditions',
      quote: '"Living history with modern hospitality."',
      author: 'Verified Traveler',
    },
  ],
  
  // Experiences
  experiences: [
    {
      id: 1,
      name: "Shepherd's Trail",
      icon: '🥾',
      duration: '4 hours',
      difficulty: 'Moderate',
      guide: 'Local mountain guide',
      description: 'Hike ancient mountain paths. Learn about shepherding, see grazing lands, stop at a traditional shepherd camp.',
      lat: 34.61,
      lng: 73.26,
    },
    {
      id: 2,
      name: 'Jabbori Bazaar Walk',
      icon: '🏘️',
      duration: '2 hours',
      difficulty: 'Easy',
      guide: 'Local market vendor',
      description: 'Explore the local bazaar. Learn traditional crafts, taste local honey, connect with villagers.',
      lat: 34.605,
      lng: 73.257,
    },
    {
      id: 3,
      name: 'Mundi Village Tour',
      icon: '🏞️',
      duration: '3 hours',
      difficulty: 'Easy',
      guide: 'Local community guide',
      description: 'Visit the neighboring Mundi village. Experience authentic village life, meet locals, taste traditional tea and snacks.',
      lat: 34.615,
      lng: 73.270,
    },
    {
      id: 4,
      name: 'Bandagocha Expedition',
      icon: '⛰️',
      duration: '6 hours',
      difficulty: 'Hard',
      guide: 'Experienced mountain guide',
      description: 'Trek to Bandagocha peak. Stunning panoramic views of the Hindu Kush range. Pack a full day adventure with lunch.',
      lat: 34.625,
      lng: 73.280,
    },
    {
      id: 5,
      name: 'Bridge Hiking Trail',
      icon: '🌉',
      duration: '2 hours',
      difficulty: 'Easy',
      guide: 'Hotel staff guide',
      description: 'Scenic hike starting from the bridge next to the hotel. Cross the bridge and explore pristine mountain paths with breathtaking valley views.',
      lat: 34.605,
      lng: 73.258,
    },
    {
      id: 6,
      name: 'Traditional Cooking Class',
      icon: '🍲',
      duration: '3 hours',
      difficulty: 'Easy',
      guide: 'Local chef',
      description: 'Cook traditional Pashtun meals. Learn recipes passed down for generations. Eat together, share stories.',
      lat: 34.606,
      lng: 73.258,
    },
    {
      id: 7,
      name: 'Golden Hour Photography',
      icon: '📸',
      duration: '2.5 hours',
      difficulty: 'Moderate',
      guide: 'Local photographer',
      description: 'Sunset photography with a professional. Capture the mountains, learn composition, share chai as light fades.',
      lat: 34.609,
      lng: 73.260,
    },
  ],
  
  // Timeline
  timeline: [
    {
      year: '1972',
      title: 'Lab e Joo Founded',
      description: 'The Khan Family established Lab e Joo as a humble retreat, sharing their mountain home with travelers seeking authentic Pashtun hospitality.',
    },
    {
      year: '1990s',
      title: 'Growth & Preservation',
      description: 'Over decades, Lab e Joo grew organically while maintaining its commitment to cultural authenticity and environmental respect.',
    },
    {
      year: '2015',
      title: 'International Recognition',
      description: 'Travelers from around the world discovered Lab e Joo, learning firsthand what melmastiya means.',
    },
    {
      year: '2020',
      title: 'Community Employment Program',
      description: '12 local families now work at Lab e Joo, bringing authentic voices and stories to every guest interaction.',
    },
    {
      year: '2026',
      title: 'Now 16 Rooms Strong',
      description: 'The commitment remains: depth over scale. Every room is a sanctuary. Every guest, a family member.',
    },
  ],
};
